### ISSUE TITLE
Change Url, Service and Root Prefix using environments variables 

### ISSUE THREAD

**Issue by jefersonmlopes** [nioc/node-red-contrib-opentelemetry#5]
Hi, 

Can I configure the attributes Url, Service and Root Prefix using the environment variables?

![image](https://github.com/nioc/node-red-contrib-opentelemetry/assets/26383949/56c0e11c-3bd8-4e5e-8077-60e4b914e28e)

My suggestions is:

OTEL_SERVICE_NAME=<service name>
OTEL_EXPORTER_OTLP_ENDPOINT=<endpoint>
OTEL_ROOT_PREFIX=<PREFIX>

**Comment by nioc** [comment]
For now, it is not possible (config vales are literal). But this can be a feature request.

**Comment by jefersonmlopes** [comment]
Do you can open the feature request?
